### ISSUE TITLE
Getting error after Findomain count result

### ISSUE THREAD

**Issue by rudSarkar** [iamthefrogy/frogy#21]
Hey,

Getting errors while scanning for the subdomain.

Error:

```bash
Findomain count: 152
cat: output/domain/dnstemp.txtls: No such file or directory
rm: cannot remove 'output/domain/dnstemp.txtls': No such file or directory
```

Looking forward to hearing from you

**Comment by iamthefrogy** [comment]
Are you getting this for all targets or any specific target?

**Comment by rudSarkar** [comment]
Hi @iamthefrogy ,

Nah, Almost every target.

**Comment by iamthefrogy** [comment]
rm: cannot remove 'output/domain/dnstemp.txtls': No such file or directory Looking at this line,

What did you give as an input to the Organization name? Did you give 'domain' and not the actual company name?

**Comment by rudSarkar** [comment]
I used the organization name for example `AirMap` not the domain. I forget to mention that I used this tool on two different devices it return the same issue.

1. `MacOS Montery 12.1` with iTerm.
2. `Ubuntu 20.04.3 LTS` with default Terminal.

Ubuntu output:

<img src="https://i.ibb.co/TtKCLtQ/Screenshot-2022-01-10-at-6-36-11-PM.png" alt="cannot remove error"/>

**Comment by iamthefrogy** [comment]
Most probably because this didn't execute dnscan well,

So in the script, I am utilizing the below Dnscan command.

python3 dnscan/dnscan.py -d .airmap.com -w wordlist/subdomains-top1million-5000.txt -D -o dnstemp.txtls

If this command executes perfectly then Frogy script should not have any problem. If this gives you an error kindly let me know what error you are getting.

**Comment by rudSarkar** [comment]
Closing this issue with PR #22 , If you like to merge go ahead and merge it.

Thanks
