### ISSUE TITLE
Importing a list of domains

### ISSUE THREAD

**Issue by zaggeb** [iamthefrogy/frogy#31]
Hello frogy,

Thank you for frogy.sh and it is great and had amazing results with it. Noticed that on wide-scope programs with wildcard domains. Frogy is lacking scaling capabilities, would it be possible to implement an argument specifying a list of hosts or modifyingt the existing interactive to accept a list. Example

bash ./frogy.sh -l domains.txt

Warm Regards,

**Comment by iamthefrogy** [comment]
Idea is to provide just 1 domain along with a specific company name and it can try to perform more horizontal and vertical both discovery. If you have multiple domains for 1 company, then no point of giving them as my script will try to anyway find that out.

If you want to run this on multiple companies then you would need to write a wrapper which can execute frogy one by one by taking company input and domain from your list but currently no plans to add that capability as I don't see a need of that.

Additionally, it's been some time it has not been updated, so I will go ahead and update this heavily.

**Comment by zagrosbingol** [comment]
That is great, a scenario as stated in youre previous comment, having a list specifying different company names and domain names.

Keep on rocking dude and know that youre work is not unnoticed. 🔥❤️

**Comment by iamthefrogy** [comment]
@zagrosbingol @zaggeb basically I have partially automated it. If you have all the primary domains, you can run frogy script using ./automate.sh for now.

Having different company names and one domain to start with is not difficult but complex problem to solve because it requires user input.

Imagine a file where you have a list of company names and another file where you will have a list of primary domains, how will you pick right company name against right primary domain to start frogy script with.

If you create a single file with company name - primary domain (e.g., Airbnb inc. - airbnb.com then it's too much hustle for you to create such text file.

Below is are the 3 recommended methods to use frogy for the best output.

1. Use this - https://www.reversewhois.io/ and identify all primary domains. Create list.txt and run ./automate.sh
2. Do crt.sh analysis and give company name instead of domain name there - Find all primary domains. Create list.txt and run ./automate.sh
3. Use Projectdiscovery CHAOS DB if your target is famous, identify all primary domains and use ./automate.sh

**Comment by zagrosbingol** [comment]
Sorry for reopening this issue and thank you for working on this and providing further feedback.

However i am unable to find the script automate.sh @iamthefrogy.
